# Generated by Django 4.0 on 2023-01-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
